### ISSUE TITLE
Previous view is hidden when modal is opened on top

### ISSUE THREAD

**Issue by KikkoMax** [nventive/Chinook.Navigation#57]
## Expected Behavior
We should be able to see the previous window when part of the modal is set to transparent (Works correctly with Chinook.SectionsNavigation.Uno.WinUI <= 2.1.0)

## Actual Behavior
Previous window is entirely hidden when a modal is opened (Chinook.SectionsNavigation.Uno.WinUI >= 2.1.1)

## Steps to Reproduce the Problem

1. Unzip UnoApplicationTemplate - hidden modal.zip and open the solution in VS2022
2. Adjust the nuget version for Chinook.SectionsNavigation.Uno.WinUI in the mobile project in order to reproduce or remove the behavior
3. Build the mobile project and execute on either android or iOS
4. Skip the onboarding, once on the login page, click on create account page which will be opened as a modal
5. Observe the behavior for the grayed out window behind

## Specifications

- Version: Chinook.SectionsNavigation.Uno.WinUI >= 2.1.1
- Platform: All platforms
- Subsystem: Windows

[UnoApplicationTemplate - hidden modal.zip](https://github.com/nventive/Chinook.Navigation/files/13956216/UnoApplicationTemplate.-.hidden.modal.zip)

**Comment by Soap-141** [comment]
Introduced by #51, will look into it.

**Comment by KikkoMax** [comment]
Version 3 with Uno 5+ please!

**Comment by jeanplevesque** [comment]
@KikkoMax You should now be able to test the fix using version 3.0.1 😃
